services:
  s3sync:
    build:
      context: .
    environment:
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_S3_ENDPOINT=http://minio:9000
      - AWS_S3_DISABLE_SSL=True
      - FROM_BUCKET=cwbi-data-develop
      - FROM_KEY=/cumulus
      - TO_BUCKET=castle-data-develop
      - TO_KEY=/cumulus
      - PARAMS=

    # command: ['tail', '-f', '/dev/null']
    # command: /bin/sh -c /app/sync.sh

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
  # configure minio on startup (create buckets, etc)
  # inspired by https://github.com/minio/minio/issues/4769
  # and         https://gist.github.com/haxoza/22afe7cc4a9da7e8bdc09aad393a99cc
  minio_init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo 'sleeping for 10 seconds while minio starts...';
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
      /usr/bin/mc mb minio/cwbi-data-develop minio/castle-data-develop;
      /usr/bin/mc policy set public minio/cwbi-data-develop;
      /usr/bin/mc policy set public minio/castle-data-develop;
      /usr/bin/mc cp --recursive /media/cwbi-data-develop/ minio/cwbi-data-develop/;
      exit 0;
      "
    volumes:
      - ./data:/media
